[package]
name = "sigmars_garden"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1"
hexx = { version = "0.22", features = ["serde"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
rdev = "0.5"
enigo = "0.6"

[profile.release]
opt-level = 3
codegen-units = 1